---
-

  hosts: localhost

  tasks:
  
    - name: Primera tarea
      debug:
        msg: 'Realizando la primera tarea'
      tags: deploy

    - name: Añadimos retraso forzado
      pause:
        seconds: 10
      tags: never

    - name: Segunda tarea
      debug:
        msg: 'Realizando la segunda tarea'
      tags: deploy
