---
# YAML documents begin with the document separator ---
 
# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-
 
  # Hosts: where our play will run and options it will run with
  hosts: localhost
 
  # Tasks: the list of tasks that will be executed within the playbook
  tasks:
    - name: Creating user directories
      file:
        dest: "/home/{{ item.0 }}/{{ item.1 }}"
        owner: "{{ item.0 }}"
        group: "{{ item.0 }}"
        state: directory
      with_nested:
        - [ pedro, luisa, maria, juan, luis, laia]
        - [ documentos, peliculas, musica ]

#loop: "{{ ['pedro', 'luisa'] | product(['documentos', 'peliculas', 'musica']) | list }}" 
...

