---



- name: Mi primer playbook con variables usando listas
 
  hosts: localhost

  vars_files:
    - auxvar04.yaml

  tasks:
    - name: Mostrar variable entera
      debug:
        msg: "{{ motd  }}"
 
    - name: Mostrar primer elemento de la lista
      debug:
        msg: "{{ motd.0 }}"
 
    - name: Equivalente al anterior pero con formato tipo python
      debug:
        msg: "{{ motd[0] }}"
 

...

