---



- name: Mi primer playbook con variables usando listas
 
  hosts: localhost

  vars:
    motd: 
      - cursoAnsible: 'Bienvenido al curso de Ansible, ahora con variables'
      - cursoDocker: 'Bienvenido al curso de Docker, con extra de variables'


  tasks:
    - name: Mostrar variable entera
      debug:
        msg: "{{ motd  }}"
 
    - name: Mostrar primer elemento de la lista
      debug:
        msg: "{{ motd.0 }}"
 
    - name: Equivalente al anterior pero con formato tipo python
      debug:
        msg: "{{ motd[0] }}"
 

...

