---

-

  hosts: linux

  tasks:
    - name: Ejecutar solamente en AMI
      command: ls -l
      when: 
        - ansible_distribution == "Amazon" #Se pueden utilizar en lista para multiples condiciones (op. AND)
        - ansible_os_family == "RedHat"
      register: ls_output

    - name: Mostrar registro
      debug:
        var: ls_output.stdout

...

